---
- name: "Prepare hosts, deploy CAs, install Rsyslog"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: "Include labocbz.prepare_host"
      tags:
        - "labocbz.prepare_host"
      ansible.builtin.include_role:
        name: "labocbz.prepare_host"

    - name: "Include labocbz.add_logrotate_confs"
      tags:
        - "labocbz.add_logrotate_confs"
      vars:
        logrotate_configurations: "{{ inv_logrotate_configurations }}"
      ansible.builtin.include_role:
        name: "labocbz.add_logrotate_confs"

    - name: "Include labocbz.add_certificates"
      tags:
        - "labocbz.add_certificates"
      loop: "{{ inv_ca_cert_bundles }}"
      loop_control:
        loop_var: bundle
      when: inv_ca_cert_bundles is defined
      vars:
        add_certificates_bundle_name: "{{ bundle.name }}"
        add_certificates_bundle_type: "{{ bundle.type }}"
        add_certificates_bundle_src: "{{ bundle.src }}"
        add_certificates_bundle_dest: "{{ bundle.dest }}"
        add_certificates_bundle_src_user: "{{ bundle.src_user }}"
        add_certificates_bundle_src_password: "{{ bundle.src_password }}"
        add_certificates_bundle_dest_user: "{{ bundle.dest_user }}"
        add_certificates_bundle_dest_group: "{{ bundle.dest_group }}"
        add_certificates_bundle_dest_mode: "{{ bundle.dest_mode }}"
      ansible.builtin.include_role:
        name: "labocbz.add_certificates"

    - name: "Install Rsyslog"
      when: inv_install_rsyslog | default(false)
      block:
        - name: "Include labocbz.install_rsyslog"
          tags:
            - "labocbz.install_rsyslog"
          ansible.builtin.include_role:
            name: "labocbz.install_rsyslog"

    - name: "Install SSH"
      when: inv_install_ssh | default(false)
      block:
        - name: "Include labocbz.install_ssh"
          tags:
            - "labocbz.install_ssh"
          vars:
            ssh_port: "{{ inv_ssh_port }}"
            ssh_administration_name: "{{ inv_ssh_administration_name }}"
            ssh_allowed_groups: "{{ inv_ssh_allowed_groups }}"
          ansible.builtin.include_role:
            name: "labocbz.install_ssh"

    - name: "Install Fail2Ban"
      when: inv_install_fail2ban | default(false)
      block:
        - name: "Include labocbz.install_fail2ban"
          tags:
            - "labocbz.install_fail2ban"
          vars:
            fail2ban_report_email_address: "{{ inv_fail2ban_report_email_address }}"
            fail2ban_ssh_port: "{{ inv_fail2ban_ssh_port }}"
          ansible.builtin.include_role:
            name: "labocbz.install_fail2ban"

    - name: "Install UnattendedUpgrades"
      when: inv_install_unattended_upgrades | default(false)
      block:
        - name: "Include labocbz.install_unattended_upgrades"
          tags:
            - "labocbz.install_unattended_upgrades"
          vars:
            install_unattended_upgrades_automatic_reboot: "{{ inv_install_unattended_upgrades_automatic_reboot }}"
            install_unattended_upgrades_automatic_reboot_time: "{{ inv_install_unattended_upgrades_automatic_reboot_time }}"
            install_unattended_upgrades_report_email_address: "{{ inv_install_unattended_upgrades_report_email_address }}"
          ansible.builtin.include_role:
            name: "labocbz.install_unattended_upgrades"

    - name: "Install Byobu"
      when: inv_install_byobu | default(false)
      block:
        - name: "Include labocbz.install_byobu"
          tags:
            - "labocbz.install_byobu"
          vars:
            install_byobu_install_neofetch: "{{ inv_install_byobu_install_neofetch }}"
            install_byobu_enable_neofetch_for_all: "{{ inv_install_byobu_enable_neofetch_for_all }}"
            install_byobu_enable_byobu_for_all: "{{ inv_install_byobu_enable_byobu_for_all }}"
          ansible.builtin.include_role:
            name: "labocbz.install_byobu"

    - name: "Install Postfix"
      when: inv_install_postfix | default(false)
      block:
        - name: "Include labocbz.install_postfix"
          tags:
            - "labocbz.install_postfix"
          vars:
            postfix_email_sender: "{{ inv_postfix_email_sender }}"
            postfix_email_sender_address: "{{ inv_postfix_email_sender_address }}"
            postfix_email_sender_api_key: "{{ inv_postfix_email_sender_api_key }}"
            postfix_aliases_addresses: "{{ inv_postfix_aliases_addresses }}"
            postfix_esmtp_banner: "{{ inv_postfix_esmtp_banner }}"
          ansible.builtin.include_role:
            name: "labocbz.install_postfix"

    - name: "Install Portsentry"
      when: inv_install_portsentry | default(false)
      block:
        - name: "Include labocbz.install_portsentry"
          tags:
            - "labocbz.install_portsentry"
          vars:
            portsentry_base_addresses: "{{ inv_portsentry_base_addresses }}"
            portsentry_ignore_addresses: "{{ inv_portsentry_ignore_addresses }}"
          ansible.builtin.include_role:
            name: "labocbz.install_portsentry"

    - name: "Install Rkhunter"
      when: inv_install_rkhunter | default(false)
      block:
        - name: "Include labocbz.install_rkhunter"
          tags:
            - "labocbz.install_rkhunter"
          vars:
            rkhunter_create_cron_job: "{{ inv_rkhunter_create_cron_job }}"
            rkhunter_cron_job_weekday: "{{ inv_rkhunter_create_cron_job }}"
            rkhunter_cron_job_minute: "{{ inv_rkhunter_cron_job_minute }}"
            rkhunter_cron_job_hour: "{{ inv_rkhunter_cron_job_hour }}"
            rkhunter_report_email_address: "{{ inv_rkhunter_create_cron_job }}"
          ansible.builtin.include_role:
            name: "labocbz.install_rkhunter"

    - name: "Install Lynis"
      when: inv_install_lynis | default(false)
      block:
        - name: "Include labocbz.install_lynis"
          tags:
            - "labocbz.install_lynis"
          vars:
            lynis_create_cron_job: "{{ inv_lynis_create_cron_job }}"
            lynis_cron_job_weekday: "{{ inv_lynis_create_cron_job }}"
            lynis_cron_job_minute: "{{ inv_lynis_cron_job_minute }}"
            lynis_cron_job_hour: "{{ inv_lynis_cron_job_hour }}"
            lynis_report_email_address: "{{ inv_lynis_create_cron_job }}"
            lynis_install_path: "{{ inv_lynis_install_path }}"
          ansible.builtin.include_role:
            name: "labocbz.install_lynis"

    - name: "Install Logwatch"
      when: inv_install_logwatch | default(false)
      block:
        - name: "Include labocbz.install_logwatch"
          tags:
            - "labocbz.install_logwatch"
          vars:
            logwatch_create_cron_job: "{{ inv_logwatch_create_cron_job }}"
            logwatch_cron_job_weekday: "{{ inv_logwatch_cron_job_weekday }}"
            logwatch_cron_job_minute: "{{ inv_logwatch_cron_job_minute }}"
            logwatch_cron_job_hour: "{{ inv_logwatch_cron_job_hour }}"
            logwatch_report_email_address: "{{ inv_logwatch_report_email_address }}"
            logwatch_output_format: "{{ inv_logwatch_output_format }}"
          ansible.builtin.include_role:
            name: "labocbz.install_logwatch"

    - name: "Install Node_Exporter"
      when: inv_install_node_exporter | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host_system_users: "{{ inv_prepare_host_node_exporter_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_install_node_exporter_certs }}"
          loop_control:
            loop_var: bundle
          when: inv_install_node_exporter_certs is defined
          vars:
            add_certificates_bundle_name: "{{ bundle.name }}"
            add_certificates_bundle_type: "{{ bundle.type }}"
            add_certificates_bundle_src: "{{ bundle.src }}"
            add_certificates_bundle_dest: "{{ bundle.dest }}"
            add_certificates_bundle_src_user: "{{ bundle.src_user }}"
            add_certificates_bundle_src_password: "{{ bundle.src_password }}"
            add_certificates_bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates_bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates_bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_node_exporter"
          tags:
            - "labocbz.install_node_exporter"
          vars:
            install_node_exporter_install_path: "{{ inv_install_node_exporter_install_path }}"
            install_node_exporter_lib_path: "{{ inv_install_node_exporter_lib_path }}"
            install_node_exporter_web_ssl_path: "{{ inv_install_node_exporter_web_ssl_path }}"
            install_node_exporter_web_config_file: "{{ inv_install_node_exporter_web_config_file }}"
            install_node_exporter_loglevel: "{{ inv_install_node_exporter_loglevel }}"
            install_node_exporter_version: "{{ inv_install_node_exporter_version }}"
            install_node_exporter_architecture: "{{ inv_install_node_exporter_architecture }}"
            install_node_exporter_ssl: "{{ inv_install_node_exporter_ssl }}"
            install_node_exporter_ssl_key: "{{ inv_install_node_exporter_ssl_key }}"
            install_node_exporter_ssl_crt: "{{ inv_install_node_exporter_ssl_crt }}"
            install_node_exporter_port: "{{ inv_install_node_exporter_port }}"
            install_node_exporter_stats_exports: "{{ inv_install_node_exporter_stats_exports }}"
            install_node_exporter_basic_auth: "{{ inv_install_node_exporter_basic_auth }}"
            install_node_exporter_basic_auth_login: "{{ inv_install_node_exporter_basic_auth_login }}"
            install_node_exporter_basic_auth_password_hash: "{{ inv_install_node_exporter_basic_auth_password_hash }}"
            install_node_exporter_user: "{{ inv_install_node_exporter_user }}"
            install_node_exporter_group: "{{ inv_install_node_exporter_group }}"
          ansible.builtin.include_role:
            name: "labocbz.install_node_exporter"

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            logrotate_configurations: "{{ inv_logrotate_node_exporter_configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"
