---
- name: "labocbz.prepare_host"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Prepare-Host.git"

- name: "labocbz.add_certificates"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Add-Certificates.git"

- name: "labocbz.install_byobu"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Byobu.git"

- name: "labocbz.install_fail2ban"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Fail2ban.git"

#- name: "labocbz.install_filebeat"
#  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Filebeat.git"

- name: "labocbz.install_lynis"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Lynis.git"

- name: "labocbz.install_portsentry"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Portsentry.git"

- name: "labocbz.install_postfix"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Postfix.git"

- name: "labocbz.install_ssh"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-SSH.git"

- name: "labocbz.install_unattended_upgrades"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-UnattendedUpgrades.git"

- name: "labocbz.add_logrotate_confs"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Add-Logrotate-Confs.git"

- name: "labocbz.install_node_exporter"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Node-Exporter.git"

- name: "labocbz.install_rkhunter"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Rkhunter.git"

- name: "labocbz.install_logwatch"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Logwatch.git"
